### ISSUE TITLE
RawQuant does not recognize .raw files in Windows

### ISSUE THREAD

**Issue by carlomartins** [kevinkovalchik/RawQuant#18]
Hi all,

As you can see in the figure below, there is some sort of error with my installation of RawQuant

![capture](https://user-images.githubusercontent.com/7212823/50651455-484e5d00-0f7b-11e9-8b6f-cb2086b5c733.PNG)

I've tried with other .raw files also, but the output is the same. 
What am I missing?

Thank you!

**Comment by chrishuges** [comment]
Hi,

We have recently moved the functionality of RawQuant to our new tool called RawTools (https://github.com/kevinkovalchik/RawTools). As such, we are no longer supporting RawQuant. Please give RawTools a try and let us know if it works for you. 

Thanks,
Chris

**Comment by kevinkovalchik** [comment]
Hello,

As Chris said, please check out RawTools instead if you are interesting in RawQuant. I do have a question about your computer system, though. Is it 64-bit or 32-bit? The error you got could be caused by running RawQuant on a 32-bit system. RawQuant uses Thermo's RawFileReader for raw file access, and unfortunately RawFileReader only supports 64-bit systems. RawTools also uses the same, so if you are using a 32-bit operating system you will run into the same problem with RawTools. If you are using a 64-bit system, hopefully RawTools will work for you!

Kevin

**Comment by carlomartins** [comment]
Thank you all!
